### ISSUE TITLE
Unrecognized textures

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#123]
There are a few instances when texture canno't be found in*.vdf archives:

1. `DOG_BODY_V0.TGA` - warg skin texture
  Referenced in `ItAt_WargFur.3DS`

2. `HUM_GRDS_ARMOR_V0.TGA` - raven's guard armor
  Referenced in `ItAr_Thorus_ADDON.3ds`

**Comment by Eulenmensch93** [comment]
I tried to look into this, and I also see that the string DOG_BODY is used in a binary file (Gothic 2 Gold/Data/Meshes.vdf) but not in the texture files.

The Resources::implLoadTexture function has a check implemented:
`if(hasFile(name)) {`
Which does not have a else path, but I can see that the code runs into that else a lot.
For example for HUM_ORGS_ARMOR_V3.TGA, is this because this is a mesh with multiple Materials attached to it?
The HUM_ORGS_ARMOR_V0 texture is found so probably this texture is used for the model right?
So is the V0..1..2..3 and so on based on the submesh count or something like that?

Otherwise I cannot find any problem with the code that is running as far as I can tell at the moment.
Are those missing textures really needed?

I would assume by the name that the DOG_BODY is used by the warg mesh, how does the model look in the game?
Does it look broken?
Or is that mesh maybe never used in the game, and there is another mesh that is used for the warg?

**Comment by Try** [comment]
Texture name resolving is a bit tricky in gothic:
`_V0` - version tag, where version is supposed to be provided, by script (via  `mdl_setvisualbody`)
`_C0` - color tag, similar to version tag
Sometimes requested version of texture does not exists, in that case `_V0` should be used.

> Are those missing textures really needed?

Yes, they are. Here are they in original game:
![изображение](https://user-images.githubusercontent.com/122894/111681609-bb261480-8823-11eb-858c-3bfb74682195.png)

**Comment by Eulenmensch93** [comment]
There does not seem to be a texture where even part of the name is "DOG".

I added some dirty debug prints to iterate over all known files.

```
std::vector<std::string> files = inst->gothicAssets.getKnownFiles("/");
        for(size_t i = 0;i < files.size(); i++)
        {
            std::cout << __PRETTY_FUNCTION__ << " - file[" << std::to_string(i) << "]: " << files[i] << std::endl;
        }
```

```
eulenmensch$ grep "file\[" /tmp/gothic.log | grep -i "dog"
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[19307]: DOG1.WAV
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[19308]: DOG1M.WAV
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[19309]: DOG2.WAV
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[19310]: DOG2M.WAV
grep: /tmp/gothic.log: binary file matches
eulenmensch$ grep "file\[" /tmp/gothic.log | grep -i "warg"
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[22341]: ITAT_WARGFUR.MRM
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[22804]: ITSC_TRFWARG.MRM
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30634]: WARG-C.TEX
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30635]: WARGATOR-C.TEX
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30636]: WARG_BODY.MDL
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30637]: WARG_BODY.MDM
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30638]: WARG_BODY2.MDM
static const Tempest::Texture2d* Resources::loadTexture(const string&) - file[30639]: WARG_BODY_V0-C.TEX
```

Seems like there are some warg textures and even WARGFUR.MRM files.
So maybe those are somehow applied by the game to the mesh?

Is there a way to spawn an item in opengothic?
So that I could verify that the texture is really missing in opengothic?

All the code that I have seen until now looks like all the names are at least encoded as strings in the game data and are not compressed.
So I should at least find the string "DOG" some where in the game data I think.

By the way, doesn't that "Warg Skin" item in your screen shoot look a lot like a wolf texture?
The texture on a warg as an enemy looks much more black I think, maybe they reused the wolf texture for the skin mesh?

**Comment by Eulenmensch93** [comment]
Ok, after reading more into the code I was able to patch the game so that I could spawn arbitrary items.

![image](https://user-images.githubusercontent.com/51380483/111851943-7b3f5a00-8915-11eb-963a-bda4a9c7cc2b.png)

So the texture is definitely missing.
In the next few days will try to add my spawn code as the marvin mode "insert" command.

**Comment by Eulenmensch93** [comment]
No other texture containing the keyword BODY looks anything like the one in your screen shot, so its not some kine of reuse of another texture.

I found a example tool in the ZenLib which extracts all the data from the .vdf files, but still no luck.

**Comment by ThielHater** [comment]
If a texture is not found, Gothic uses the DEFAULT texture as a fallback and it looks as this is the case here.

**Comment by Eulenmensch93** [comment]
Good catch, did not think that it could be the DEFAULT texture.

After being stupid for 2h, I finaly got the use of the texture hardcoded for the warg skin.
Looks a bit bright to me, but maybe this is just the difference in light calculations.
What do you think?

The left one was spawned, the right ones were dropped from the inventory and fell over :)

![image](https://user-images.githubusercontent.com/51380483/131378904-5b5fe1fd-a3c9-4f92-b56d-786a0d53fb45.png)

**Comment by Try** [comment]
Tested locally on my machine: seem to work fine with DEFAULT.TGA
@Eulenmensch93 wanna me to commit changes, or you will do PR?

**Comment by Eulenmensch93** [comment]
> Tested locally on my machine: seem to work fine with DEFAULT.TGA
> @Eulenmensch93 wanna me to commit changes, or you will do PR?

Feel free to commit yourself, I think its less work since the change is probably not that big.
Also I only implemented to use DEFAULT.TGA in case that we are trying to load to texture that is not found (implemented as a special case), just for testing. Did not implement the fallback in case that we would return null in impLoadTexture function.
