### ISSUE TITLE
Disabling shadows and returning old graphics?

### ISSUE THREAD

**Issue by padsp-64** [Try/OpenGothic#173]
Hello. I compiled OpenGothic for Linux and I want to say thank you for making it for Linux! However, after launching, I was disappointed - low fps and new graphics. Of course, I have nothing against it, but I would like to know: is it possible to turn off shadows and return the old graphics? Playing under Wine is not an option, I would like it with OpenGothic

Thanks in advance! =)

P.S.: I speak Russian, so if you know Russian, you can answer it

**Comment by Try** [comment]
Hi, @XServerLinuxoid !

> is it possible to turn off shadows and return the old graphics?

Just turning off shadow not implemented, but should be quite easy to implement, by using 1x1 texture instead of shadow-map (see renderer.cpp).
For true "old graphics" - that will require a whole new set of shaders, to emulate DX7 look

> disappointed - low fps

What is your hardware and fps numbers? Just want to point out that gothic is also CPU intensive - that can be a cause of low fps.

> I speak Russian, so if you know Russian, you can answer it

For github I would suggest to stick to english, so everyone else can read conversation.
You can also contact me on https://worldofplayers.ru/threads/41765, if Russian talk is more comfortable to you.

**Comment by XServerLinuxoid** [comment]
Thanks for the answer, Try =)

> What is your hardware and fps numbers? Just want to point out that gothic is also CPU intensive - that can be a cause of low fps

My hardware (is notebook): Intel Core i5-5200U, Nvidia GeForce 920M, 8 GB RAM.
The hardware is of course quite weak, but I think Gothic 2 should work fine on it. I would play under Wine in the Windows version of the game, but I would like to try the native implementation. I was also pleasantly surprised that finally Gothic 2, thanks to OpenGothic, runs on a discrete video card, and not on an integrated one - the Windows version under Wine did not run on a discrete GPU in any way. But at the same time, my fps does not exceed 23. On the built-in video core - 12 fps :(

I sin in the shadows, because with the DX11 implementation mod in Gothic 2, the situation is the same: turn on shadows - FPS drops to 20, turn off - rises to 40-45


> You can also contact me on https://worldofplayers.ru/threads/41765, if Russian talk is more comfortable to you

Okay, I understand you. Thank you =)

**Comment by Try** [comment]
> The hardware is of course quite weak

Well, by HW is I7 +  960M, so we should be close in performance(unless Linux drivers). Maybe you can try latest master, to check if issue is same as here: #176?
