### ISSUE TITLE
CMake install missing for Gothic2Notr binary and MoltenTempest shared object

### ISSUE THREAD

**Issue by swick** [Try/OpenGothic#32]
Right now `make install` completely fails for a number of reasons:

1. an `install` macro for the `Gothic2Notr` binary is missing so the binary doesn't get installed at all
2. an `install` macro for `libMoltenTempest.so` is missing. Alternatively MoltenTempest can switch to building a static library instead.

Running directly from the build dir is also broken on linux. If you want to link MoltenTempest as a shared library, `LD_LIBRARY_PATH` has to be set to the `CMAKE_LIBRARY_OUTPUT_DIRECTORY` directory in a wrapper script (or you start linking it statically).

Another point is that you should not overwrite `CMAKE_BINARY_DIR` at all! The user chose the build dir for a reason. You can still support running from the build dir.

**Comment by Try** [comment]
Hi, swick!

You absolutely right - there is no proper support for install at the moment. Mostly because at developer I don't want to have something like `make install` for debug builds. And as user - I prefer to have prebuilt binary, instead of building from sources.
 
So far I've found that overriding `LD_LIBRARY_PATH` works good enough for debug builds.
For `CMAKE_BINARY_DIR` - I've test it for a bit after your report:
yes, it can be removed from CMakeLists.txt, `CMAKE_RUNTIME_OUTPUT_DIRECTORY and CMAKE_LIBRARY_OUTPUT_DIRECTORY` is enough to place executable in correct directory.

**Comment by swick** [comment]
Alright, I opened pull requests for MoltenTempest and OpenGothic. I believe the changes should work fine on Windows, too but I can't test that.

I noticed that you set compiler options for debug (-g) but if you want a debug build you should call cmake with -DCMAKE_BUILD_TYPE=Debug or RelWithDebInfo for just the symbols. You can then set -DBUILD_SHARED_LIBS=yes/no to either statically or dynamically link all deps. All binaries and libraries will be build in $builddir/bin so on Windows you should be able to just launch the binary directly and on linux I added a wrapper script which sets LD_LIBRARY_PATH. Make install now also works.

**Comment by swick** [comment]
Thanks! The next blocker is case-sensitive support but we're getting there.
