### ISSUE TITLE
OpenAL crash on startup

### ISSUE THREAD

**Issue by pokorm** [Try/OpenGothic#38]
Hi, I just found and want to try this awesome project! But I have a problem with launching the game.

I'm running the command
```
./Gothic2Notr.exe -g "D:\Steam\steamapps\common\Gothic II"
```
which immediately outputs
```
AL lib: (EE) WinMMOpenPlayback: waveOutOpen failed: 1

---crashlog(std::system_error(No device))---
GPU: ?
[no call frames available]
```

By googling that error, it looks like it comes from external lib **OpenAL** ([winmm.c#L328](https://github.com/dougbinks/openal-soft-OLD/blob/master/Alc/backends/winmm.c#L328)). Some incompatibility with my sound card maybe? I don't know, but I tried two different Gothic II Notr versions, so it shouldn't be the problem. I'm using Windows 10.

**Comment by Try** [comment]
Hi, @pokorm ! Thanks for bug-report.

Yes, seem like waveOutOpen failed with MMSYSERR_ERROR inside OpenAL implementation.
>  I don't know, but I tried two different Gothic II Notr versions

Original uses directsound, not winmm - so it's not very representative.
Unfortunately I don't have a solution right here-now, since MMSYSERR_ERROR documented quite poorly - seem like it's more like "internal error" for winmm.
But, as alternative solution, to straightup fix, I can enable dsound for openal as fallback audio api on next release.

**Comment by Try** [comment]
I've added dsound-backend support in build 453 - in principle problem should be fixed by this

**Comment by pokorm** [comment]
I can confirm, that this is fixed for me now. Thanks ;-)
