### ISSUE TITLE
Water shader issues

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#388]
I'm not sure if this is related to #261 or to #380 or it stands on its own, hence creating a separate issue. There are several cosmetic issues that only appear when water is involved, all of which were reproduced as of 588f099119e6b8ed30ff3f18328de81df887af24 in or near the harbor:

* ship masts throw a bit of [unnatural shade](https://user-images.githubusercontent.com/6383928/213580108-97a58d5f-2c03-4733-b5ab-46965408727b.jpg)
* harbor crane hook can project similar [shade](https://user-images.githubusercontent.com/6383928/213580389-6c40fabb-15e1-439c-99db-162e84409e25.jpg) as well, though not very obvious
* objects close-ish to the camera can cancel distant geometry's reflections (tavern beam [cancelling](https://user-images.githubusercontent.com/6383928/213580636-cee0cd53-439c-49fa-b07f-2e23415570cc.jpg) a shipwreck reflection, player character [cancelling](https://user-images.githubusercontent.com/6383928/213580648-cd624790-4b33-4b85-9e9f-c127079f47c4.jpg) an island reflection)
* when diving, the underwater effect is not present
* when diving, seabed is reflected in the water surface as if above water

**Comment by Try** [comment]
Hi, @Nindaleth !

Those issue can be separated into 2 categories:
1. Reflections: those are expected artifacts of SSR shader
2. Underwater(diving) effects - those are unimplemented yet

**Comment by dreimer1986** [comment]
![dbg](https://user-images.githubusercontent.com/29841368/214132532-1495cea1-6997-4c16-a4ff-88f1948e26c5.png)
Another one I ran into recently and was quite easy to separate from the "how it should look" state.
Should be the close-ish objects aka number three of the list of @Nindaleth

**Comment by Try** [comment]
Some thoughts about water in general:

1. Need to decouple absolution and reflectance into 2 different shaders. 
2. Reflectance should have 2-3 variants;
  * Sky only
  * SSR
  * RayQuery (ray-tracing will fix this issue, right? :) )
3. Need a decent way to synthesize water displacement
  After checking bunch of sources - `exp(sin(x))` seem to be good at small frequencies and Gerstner at high 
4. Need to throw tessellation away: tessellation is unsupportable mess. Mesh shader would be more convenient

**Comment by Try** [comment]
Current progress on waves:
![изображение](https://user-images.githubusercontent.com/122894/233869679-b7dd5cd9-1e66-4fa2-a501-0073df711dbc.png)

**Comment by dreimer1986** [comment]
Looks so realistic that looing at the pic makes the brain think it's moving. I like em.

Btw, be careful with waves getting too massive if water gets the same shader everywhere in the game. https://github.com/Try/OpenGothic/commit/9d365273ccf6e67e7551e49a8912aa1e9452db12 made lil rivers look like a hell of a storm is moving along over them. Just found out yesterday and did not have time to report yet.

**Comment by Try** [comment]
Water surface:
![изображение](https://github.com/Try/OpenGothic/assets/122894/c2115719-b57c-4c11-884c-2df29b988096)

Underwater:
![изображение](https://github.com/Try/OpenGothic/assets/122894/321d2b61-55a1-4c2a-a8d9-4fdbc1961788)

Offended view, in pirate camp:
![изображение](https://github.com/Try/OpenGothic/assets/122894/9f4b1a85-8e7b-4e43-a8ee-205216c567f9)

Offended view in harbor:
![изображение](https://github.com/Try/OpenGothic/assets/122894/8a51144d-b2d6-4d2b-9aa7-b9440c1c1554)
![изображение](https://github.com/Try/OpenGothic/assets/122894/6fd74a65-a49e-4a33-855d-ac9d17802247)


For underwater case, there is clear lack of scattering component, since it's too tricky to estimate water depth.
Also, just realize that I don't want to do ray-tracing version :D
