### ISSUE TITLE
Lothar does not tell the rules of the town

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#414]
Steps to reproduce:
1 load the attached save
2 give the papers to sentinels
3 approach to Lothar
Observed:
Nothing happens. When clicking on Lothar he shouts something like "Don't disturb me" (I run different localization)
Expected:
Lothar starts telling the the rules to the Chosen One.
[save_slot_6.sav.gz](https://github.com/Try/OpenGothic/files/10786437/save_slot_6.sav.gz)

Additional info: I was unable to bisect because save did not load

**Comment by Try** [comment]
Hi, @AlexJakeGreen and thanks for reporting!

This is likely caused by sneaking mechanics;
player emits `PERC_ASSESSQUIETSOUND` when walking and `PERC_ASSESSPLAYER`, when close to npc.
Due to poorly written scripts, this can cause clean state for npc sometimes, so they can't react to anything.

At this point we probably need to guess exact, as in vanilla game, execution order for perceptions.

**Comment by AlexJakeGreen** [comment]
It worked before. Lothar did not let pass him without listening to him.

**Comment by AlexJakeGreen** [comment]
First appears in 16e37c5b2a8ab97dd197a6fe2355c0c11fab38e3

**Comment by Try** [comment]
Here is quick-fix: [d840f42](https://github.com/Try/OpenGothic/commit/d840f421b4fcdfa2bd24f130486252a189516330)
Yes, still need to verify, how reliable it is.

**Comment by AlexJakeGreen** [comment]
The fix helps. Now Lothar is talking.
