### ISSUE TITLE
Case sensitiveness issue on linux

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#51]
Hello.

First of all: Wow. This is an amazing project. Thank you for this.

I tried to compile and start the project on a linux machine.
After installing _CMake_ 3.12 from a third party repo (kitware) and installing _glslang-tools_ it built very smooth with only one warning so far. Nice.

After starting a new game, it turned out, that the player controls were'nt working. I debugged a bit and discovered that
```cpp
std::unique_ptr<IniFile>                baseIniFile;
std::unique_ptr<IniFile>                iniFile;
```
couldn't be found. Therefore all control keys were unset.
The reason, why the files could'nt be found, was the following:
In my installation (German CDs: Gothic II Normal + Addon) the folder and ini file was named in different case:
"_System/Gothic.INI_" instead of "_system/Gothic.ini_".
After I renamed the folder and the file, the player controls has been working.

For a general solution, I digged myself down in the code and made the following observations:

1. I found pieces of code, that might be required to solve the problem in the following places:
- Game/utils/fileutil.h: exists
- Game/utils/fileext.h: hasExt, exchangeExt
- Game/gothic.h: caseInsensitiveSegment
- lib/MoltenTempest/Engine/utility/dir.h: scan

2. String conversions are done at various places and the usage seems to have been mixed up sometimes (I've seen so far: char*, std::string, std::u16string, unicode 8 conversion being used as std::wstring). That's just a subjective impression.

I want to offer you the following changes, but want to ask for your opinions beforehand:
- Implementation of dedicated String classes, that are inheriting from the std::string, std::wstring, etc. and implement support functions, that are required at different places (toUpper, toLower, indexOf, equals, replace, trim, conversion from string/wstring/u16string,u32string to each other string).
- Implementation of a path class, that would be an specialization of the upper listed String class, that handles often required functions: getFilename, getExtension, getFilenameWithExtention, isAbsolute, isRelative, dirUp or concatenation of paths.
- After that an explorer class might be useful, to search for files / directories recursively or not and case sensitive or not. This class might be implemented with std::expermimental::fs features that should be available at >= c++14.

What do you think about that approach ? Do you want to have it done that way ?
The way of not specializing the std::string and using more static support functions might be a good approach, too. It would look more like the std::string instead of yet another custom util string.

I'm curious about your opinions :+1:

**Comment by Try** [comment]
Hi,  @ErrorFlexXx and thanks for bug-report!
About paths and strings: there are 2 types of paths actually the first is 'real path' and the second is 'asset path'
Real paths are very rare case for gothic, relates only to *.vdf archives, *.ini, *.sav, directx-sound files.
Asset path is common case, relates to textures, meshes and scripts in *.vdf archive.
All asset-paths **can** be represented as `char[64]`, but usually it's std::string or const char*.

With that said, string convention at this moment is:

1. std::u16string - real file path
2. std::string/const char* asset file path. const char* is used where necessary, to avoid extra copy-constructors.
3. ZString(aka std::shared_ptr<std::string>) - a immutable string class designed explicitly for Daedalus script.

>I want to offer you the following changes, but want to ask for your opinions beforehand

Since OpenGothic doesn't use real-file path all too often, intent was to keep implementation as simple as possible:
u16string as filepath + Dir::scan + Gothic::nestedFilePath.

Note: nestedFilePath is a bit unique to project - this function is used to align windows-like case insensitive path to unix-like case-sensitive path.

Back to the issue itself, fix can be done by changing one line:
```c++
-  baseIniFile.reset(new IniFile(gpath+u"system/Gothic.ini"));
+  baseIniFile.reset(new IniFile(nestedPath({u"system",u"Gothic.ini"},Dir::FT_File)));
```
