### ISSUE TITLE
Summoned beasts do not attack enemies after throwing spell

### ISSUE THREAD

**Issue by polaskin** [Try/OpenGothic#561]
After summoning a beast, eg. a skeleton, if I throw a spell, that does damage at an enemy the skeleton will not attack it, until the enemy hits me. That only happens with magic spells or runes. If I hit the enemy with an arrow or with a weapon, the skeleton will attack him immediately.

**Comment by Try** [comment]
Tested on vanilla, they do not react in this particular case as well:
![изображение](https://github.com/Try/OpenGothic/assets/122894/548f64d6-a7b8-4e1b-abb7-93ac5c145695)

Enemy should be in ~10 meter proximity for summoned skeleton to react.

There were some missing pieces on reaction distance (fixed range, instead of script-driven) - fixed in feed5822
