### ISSUE TITLE
Launching Gothic 1 should imply Gothic 1 controls as default

### ISSUE THREAD

**Issue by oaken-source** [Try/OpenGothic#595]
The game seems to default to Gothic 2 controls, unless useGothic1Controls=1 is specified in Gothic.ini.

This is okay, unless you launch Gothic 1, which of course doesn't include this setting in a standard install. This has caused me some head scratching and digging to figure it out, and I think it would be clearer to default to the Gothic 1 control schemes if Gothic 1 is launched (for example triggered by the -g1 command line flag?)

**Comment by oaken-source** [comment]
And I also notice that the setting for Gothic 1 controls seems to only change the fighting style of the game, not interactions with objects? I can pick up items on the ground just by pressing one key, as opposed to the key+direction combo required by the original.

**Comment by Try** [comment]
Hi @oaken-source !

Yes, G1-controls are affecting only a fighting style, as it was in original G2 game. And since G1 is not officially supported, dedicated control scheme was simply not implemented.

> it would be clearer to default to the Gothic 1 control schemes if Gothic 1

Yes, you right. This was not intentional, and I think `useGothic1Controls=1` can be default for both games, as it most popular one.
