### ISSUE TITLE
Neoras gives a potion, but it does not appear in backpack

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#705]
Neoras cooks a potion of Dexterity/Geschicklichkeit (expected), then we can see a message that it gives a potion to the player (expected), then check backpack – no new potion there (not expected).

[save_slot_7.sav.gz](https://github.com/user-attachments/files/18205488/save_slot_7.sav.gz)

GOG DE version.

**Comment by Try** [comment]
Hi, @AlexJakeGreen and thanks for report!

I've checked your save file, and there seem to be no dexterity option in menu:
![изображение](https://github.com/user-attachments/assets/511ca418-2383-4403-99f7-e258147ae6bd)

Maybe it's due to my running it on top of English version. I've also checked available potions, and speed-potion i particular, - they do work just fine.

Maybe it's bug with scripts specifically in GOG-DE version.

**Comment by AlexJakeGreen** [comment]
Hi! Thanks for re-checking! I was confused with speed and agility, it was late or my eyes do not serve me anymore. Sorry for taking your time. Thanks for continuous work on the engine.
