### ISSUE TITLE
[Linux/Fedora 31] Segmentation fault on startup

### ISSUE THREAD

**Issue by jdobes** [Try/OpenGothic#74]
compiled from freshly cloned master:
```
$ ./opengothic/Gothic2Notr.sh -g /home/jdobes/.steam/steam/steamapps/common/Gothic\ II/
no *.ini file in path - using default settings
GPU = Intel(R) UHD Graphics 620 (Kabylake GT2)
Depth format = 6 Shadow format = 4
Segmentation fault (core dumped)
```

valgrind log: https://pastebin.com/bSbwiP7Z

**Comment by Try** [comment]
Hi, @jdobes and thanks for report!

From Valgrind log: engine tries to write into mapped memory, allocated by libvulkan_intel.so - what is completely fine.
Possibly this issue related to incomplete vulkan support on Linux, by intell.

Does other vulkan content run on your machine?
Can you run the game with validation layer ( `-v` in command line )?

**Comment by jdobes** [comment]
Running with `-v` doesn't seem to change anything. I'm able to run games using DXVK so I guess it should work. Adding my vulkaninfo output and GDB backtrace.

https://pastebin.com/WBH9qt6p
https://pastebin.com/A1uaYGpq

**Comment by Try** [comment]
> Running with -v doesn't seem to change anything.

Yes, that's how it suppose to work: validation prints message if invalid api-call detected.

I've also checked on `Intel(R) HD Graphics 530` + Win10 setup - game works without errors.
HD530 is the closest setup, I have.

My current view on the problem: driver-level issue, can be avoided.
Since DXVK work well on your machine, key to fix can be in memory-types:
 OpenGothic uses non-coherent memory,
 DXVK, probably, uses `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`, since memory in directx is coherent.

Can't progress much on this issue, since it unreproducible on my hardware/os.

**Comment by PolyMeilex** [comment]
@jdobes Are you on Wayland by any chance? If so try to check if your XWayland server is able to run hardware acceleration. It's known for breaking on some hardware, I guess intel should work fine but it's worth checking.

**Comment by Try** [comment]
Found the bug: gpu-memory mapping range was smaller then it should be
