### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by smaTc** [Try/OpenGothic#81]
First of all: Great work!
I know there is some kind of a multiplayer mod but if I remember correctly it is only the world and no quests.
Would it be possible with this engine to implement a working multiplayer? Or is it not possible because of the content files from Zengin and the handling by LibZen?

**Comment by Try** [comment]
Hi, @smaTc and thank for question!

Short answer: a lot of work, but possible.

Long answers:
Let me do a quick recap on current project state and changes required for multiplayer mode:
1. There is no network subsystem in project - no big deal, since there are many c/c++  network libraries.

2. Game mechanic is time-based in OpenGothic - for each player state calculation going to be slightly different:
![изображение](https://user-images.githubusercontent.com/122894/87716282-ed700580-c7ae-11ea-868c-0fe3b257ec2a.png)
That makes hard to synchronize game-state across players.

3. Game world features many npc and monsters - that's a lot of data to be synchronized
    * Approach, like lock-step (common for RTS) is not possible, because `2)
    * Make server to broadcast state-change for each client is not efficient with large amount of npc/monsters

4. Gothic script-logic is not network friendly. Most of game quests track player progress as global state, all of them has to be changed to be playable online

**Comment by smaTc** [comment]
1. Indeed network code itself is no problem
2. Can be catched with inter/extrapolation to a certain degree I think
3. state interpolation should work on this. And maybe limit clients for a max of 2-4. Should limit the data overhead. So at least a coop mode ist possible
4. Is this something that your engine decides or the Zengine files you need to use?

**Comment by smaTc** [comment]
by the way: git clone for linux does not pull all submodules correctly (ZenLib was not pulled)

**Comment by Try** [comment]
> Is this something that your engine decides or the Zengine files you need to use?

Game script is a part of 'game content'. On OpenGothic side of things scripts are precompiled byte-code consists of simple instructions, like 'add', 'mul', 'invoke' - not much can be done on engine side.
On the other hand: scrips are can be modified by using mod-kid, so it's possible to fix in-game quests, but the subject is out of scope of OpenGothic

>git clone for linux does not pull all submodules correctly 

May be you forgot to `git submodule  update --init --recursive` ?

**Comment by smaTc** [comment]
`git submodule update --init --recursive` also returns an error seemingly caused by the zenlib repo. Error (translated):
```
fatal: Error on other end: upload-pack: not our ref e8e87dbd059bb349e1fae27c87fa4d6540622806
fatal: Remote canceled unexpectedly.
"fetch" in Submodul-Path 'lib/ZenLib' executed, but e8e87dbd059bb349e1fae27c87fa4d6540622806 not found.
Direct pull failed
```
